name: Ejercicio de acción compuesta
description: 'Build npm'
inputs:
  version-node:
    required: true
    type: number
    default: 18
    description: "La versión de node en la que queremos probar"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup node environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version-node }}
    - run: npm ci
      shell: bash
    - run: npm test
      shell: bash